name: supercycle
description: Super re:cycle
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sentry_flutter: ^7.10.1
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  kakao_flutter_sdk: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
